name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create /modules/apiKey.js with secret key
        run: |
          mkdir -p modules
          echo "export const API_KEY = '${{ secrets.API_KEY }}';" > modules/apiKey.js

      - name: Build site (if you have a build step)
        run: |
          # e.g., npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public  # or your build output folder
